version: '3.3'
services:
  docker-mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: cartago
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=mocks
    ports:
      - 3306:3306